### ISSUE TITLE
Slurm 18.08 support

### ISSUE THREAD

**Issue by kcgthb** [OSC/ood-activejobs#169]
Hi there!

We just upgraded our Slurm version to 18.08.3, and it looks like some command output formatting may have changed and broke the listing of jobs.

The active job list is now empty and shows an error message: "undefined method `split' for nil:NilClass"

![image](https://user-images.githubusercontent.com/186807/49199223-89839980-f34b-11e8-8410-14dfac0733c2.png)

Could you please point us out to where we should look to fix this? Thanks!

**Comment by ericfranz** [comment]
Slurm 17 had a `gres` column in the output, where as Slurm 18 does not.

This fix is a work in progress https://github.com/OSC/ood_core/pull/105. Right now the approach is to specify a version in the cluster config, and if its >=18 we remove `gres` from the output we are parsing. I wonder if there is a more robust/safe way to parse the output so that if this changes again in Slurm 19 we can handle that, or if its just something we will have to deal with. The 1.4 release will have this fix included and I think we are now targeting for end of next week or the week after.

If you need the fix earlier there are two options:

1. If you are using the /latest/ branch of rpms for OnDemand, we will be releasing a new one Friday or early next week. Note that will also have an upgrade to Passenger and NGINX so may require an extra installation step.
2. If you need a fix now I can provide the small monkey patch that you can add to your /etc/ood/config/ directory in three places (for dashboard, active jobs, and job composer) to make those work again. Let me know.

**Comment by kcgthb** [comment]
Hi Eric,
Thanks a lot for the info! A quick patch would be awesome to restore functionality before the next RPM release.

Thanks!

**Comment by MorganRodgers** [comment]
@kcgthb attached is a script that will patch this issue. As Eric noted, our next release of OOD will contain a proper fix.

To patch run: `sudo bash patch_slurm18.sh.txt patch`
To remove the patch: `sudo bash patch_slurm18.sh.txt unpatch`

[patch_slurm18.sh.txt](https://github.com/OSC/ood-activejobs/files/2630324/patch_slurm18.sh.txt)

**Comment by kcgthb** [comment]
@MorganRodgers Thanks a lot, that works perfectly!

**Comment by MorganRodgers** [comment]
@kcgthb FYI I just discovered that the source of this problem appears to be a bug in Slurm: https://github.com/OSC/ood_core/pull/105#issuecomment-442975956

**Comment by kcgthb** [comment]
Right, we noticed that yesterday too, and a colleague of mine reported it at https://bugs.schedmd.com/show_bug.cgi?id=6120

**Comment by MorganRodgers** [comment]
Look at that. I missed that when searching for issues. If you all are into patching Slurm @treydock just posted a patch to the issue that I opened which fixes this problem.
