### ISSUE TITLE
Ensure jobs link to appropriate terminal host.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-activejobs#58]
The terminal button is currently configured to display the "Default" configured shell. On our system, that's always Oakley.

User reports it's confusing to always be put on Oakley when submitting jobs on Owens.
https://oarnet.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=e970eff2dbfd26004a8a7d3ebf961947%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true

The [JobStatusData](https://github.com/AweSim-OSC/osc-jobstatus/blob/master/app/models/jobstatusdata.rb#L52) model should be updated to use the OodAppkit shell helper which now includes the ability to specify the host. See: https://github.com/OSC/ood_appkit#shell-app

**Comment by ericfranz** [comment]
So without looking at too much code, it seems that the solution to this is:

1. pass in cluster to Jobstatusdata.new instead of cluster id
2. set cluster id to `Jobstatusdata#cluster` like normal
3. if `extended==true`, add a new attribute to specify the shell URL by updating this line: https://github.com/OSC/ood-activejobs/blob/master/app/models/jobstatusdata.rb#L52 following your suggestion to check if `login_server?` set

**Comment by basilgohar** [comment]
I'm assigning this to the Open OnDemand project because I think this is not OSC-specific.  Other centers may have multiple clusters configured, as that's a feature we provide.
